### ISSUE TITLE
Can´t use moveend on body and expect document scrolling to work on mobile devices.

### ISSUE THREAD

**Issue by AndersBillLinden** [stephband/jquery.event.move#27]
On

https://jsfiddle.net/twjou50r/1/embedded/result/

I have a webpage where scrolling does not work very well on mobile devices.
I am using the emulation in chrome to try this. A phone will also prove the issue.

Problem: Nothing happends when I try to scroll, even if document content is taller than the window.

If I remove the lines

    $('body').on('moveend', function ()
    {
        /* something */
    });

scrolling works as demonstrated on:
https://jsfiddle.net/twjou50r/2/embedded/result/

(if you want to see the source of those jsfiddles, you click "Edit in JSFiddle")

**Comment by stephband** [comment]
If you bind a move event to the body, the script assumes you want to move, not scroll, the body. To conditionally suppress scrolling, see the documentation here:

http://stephband.info/jquery.event.swipe/#scroll

**Comment by AndersBillLinden** [comment]
What I really want is to check if the mouse is released anywhere in the document. (Still having the possibility to scroll the document). I only have a handler 'movestart' in a certain element, not in body.

**Comment by stephband** [comment]
Yes I see. You want to delegate moveend to handle all moveends for the document. But moveend cancels scroll because it assumes you're listening for a move, not a scroll. You should be able to set up a movestart also on the body, use it to enable scrolling (by calling .preventDefault() if event.target is not one of the things you want to move), and the moveend handler will still pick up delegates from the things you have moved.

It's a bit tricky getting jQuery special events to delegate nicely, and the move events weren't designed with this use case in mind. Should work, though.

**Comment by AndersBillLinden** [comment]
I ended up checking target in the moveStart handler.

````javascript
$('body').on('movestart', function(e)
{
  if ($(e.target).closest('.event-slider .scrolled-content').length == 0)
    e.preventDefault();
});
````

Thanks for the help!
